[build]
  command = "node generate-fontlist.js"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "multer"]

[build.environment]
  NODE_VERSION = "14"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/api/font/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Cache-Control = "public, max-age=31536000"

# FontのMIMEタイプを設定
[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Content-Type = "font/ttf"

[[headers]]
  for = "*.otf"
  [headers.values]
    Content-Type = "font/otf"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 